# Generated by Django 5.2.11 on 2026-05-21 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0003_seed_default_clarivo_plans"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="business_type",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
