# Generated by Django 5.2.11 on 2026-05-21 00:44

from django.db import migrations, models


def backfill_business_address_line_1(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")

    for business in Business.objects.exclude(address="").filter(address_line_1=""):
        first_line = next(
            (
                line.strip()
                for line in business.address.splitlines()
                if line.strip()
            ),
            "",
        )
        if not first_line:
            continue

        business.address_line_1 = first_line[:255]
        business.save(update_fields=["address_line_1"])


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_business_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="address_line_1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="business",
            name="address_line_2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="business",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="business",
            name="default_locale",
            field=models.CharField(blank=True, default="", max_length=35),
        ),
        migrations.AddField(
            model_name="business",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="business",
            name="region",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="business",
            name="tax_label",
            field=models.CharField(blank=True, default="Tax", max_length=40),
        ),
        migrations.RunPython(
            backfill_business_address_line_1,
            reverse_code=noop_reverse,
        ),
    ]
