# Generated by Django 5.2.11 on 2026-06-25 21:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0008_update_motionmate_plan_descriptions"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessBookingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("booking_enabled", models.BooleanField(default=False)),
                (
                    "default_duration_minutes",
                    models.PositiveIntegerField(
                        default=60, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "minimum_notice_hours",
                    models.PositiveIntegerField(
                        default=24, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "maximum_days_ahead",
                    models.PositiveIntegerField(
                        default=30, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "buffer_minutes",
                    models.PositiveIntegerField(
                        default=0, validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "confirmation_mode",
                    models.CharField(
                        choices=[
                            ("request_only", "Request first / manual confirmation"),
                            ("auto_confirm_later", "Auto-confirm later"),
                        ],
                        default="request_only",
                        max_length=30,
                    ),
                ),
                ("public_booking_instructions", models.TextField(blank=True)),
                ("cancellation_policy_text", models.TextField(blank=True)),
                ("reschedule_policy_text", models.TextField(blank=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="booking_settings",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "business booking settings",
                "verbose_name_plural": "business booking settings",
                "ordering": ["business__name"],
            },
        ),
        migrations.CreateModel(
            name="WeeklyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ]
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekly_availability",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name": "weekly availability",
                "verbose_name_plural": "weekly availability",
                "ordering": ["day_of_week", "start_time", "pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "day_of_week", "is_active"],
                        name="businesses__busines_a82057_idx",
                    )
                ],
            },
        ),
    ]
