# Generated by Django 5.2.11 on 2026-06-27 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_businessbookingsettings_weeklyavailability"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyavailability",
            name="staff_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="availability_blocks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyavailability",
            index=models.Index(
                fields=["business", "staff_member", "day_of_week", "is_active"],
                name="businesses__busines_4a48b6_idx",
            ),
        ),
    ]
