# Generated by Django 5.2.11 on 2026-07-11 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0013_motionmate_final_tiers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserOnboardingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("selected_journey", models.CharField(blank=True, max_length=80, null=True)),
                ("completed_welcome", models.BooleanField(default=False)),
                ("dismissed_at", models.DateTimeField(blank=True, null=True)),
                ("skipped_steps", models.JSONField(blank=True, default=list)),
                ("last_step_key", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_states",
                        to="businesses.business",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["business__name", "user__email"],
                "indexes": [
                    models.Index(
                        fields=["business", "user"], name="businesses__busines_9bad1f_idx"
                    ),
                    models.Index(
                        fields=["business", "selected_journey"],
                        name="businesses__busines_5324e6_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "business"),
                        name="businesses_onboarding_unique_user_business",
                    )
                ],
            },
        ),
    ]
