# Generated by Django 5.2.11 on 2026-07-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0015_seed_internal_beta_plan"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscription",
            name="billing_currency",
            field=models.CharField(
                blank=True, choices=[("usd", "USD"), ("eur", "EUR")], default="", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="billing_interval",
            field=models.CharField(
                blank=True,
                choices=[("monthly", "Monthly"), ("yearly", "Yearly")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="checkout_session_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="payment_provider",
            field=models.CharField(
                blank=True,
                choices=[("local", "Local"), ("stripe", "Stripe")],
                default="",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_checkout_session_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_price_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="businesssubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_checkout", "Pending Checkout"),
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("suspended", "Suspended"),
                ],
                default="trialing",
                max_length=20,
            ),
        ),
    ]
