# Generated by Django 5.2.11 on 2026-07-18 15:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0016_subscription_checkout_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingProviderWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("stripe", "Stripe")], default="stripe", max_length=30
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=120)),
                ("object_id", models.CharField(blank=True, default="", max_length=255)),
                ("api_version", models.CharField(blank=True, default="", max_length=64)),
                ("livemode", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("processing", "Processing"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                            ("ignored", "Ignored"),
                        ],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("received_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                ("payload_summary", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["-received_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="last_payment_failure_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="last_payment_failure_reason",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_customer_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_subscription_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="provider_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="businesssubscription",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_subscription_id", ""), _negated=True),
                fields=("payment_provider", "provider_subscription_id"),
                name="businesses_unique_provider_subscription",
            ),
        ),
    ]
