# Generated by Django 5.2.11 on 2026-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0017_provider_webhook_sync"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businesssubscription",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_checkout", "Pending Checkout"),
                    ("trialing", "Trialing"),
                    ("active", "Active"),
                    ("past_due", "Past Due"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                    ("suspended", "Suspended"),
                ],
                default="trialing",
                max_length=20,
            ),
        ),
    ]
