# Generated by Django 5.2.11 on 2026-07-18 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0018_subscription_expired_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="businesssubscription",
            name="grace_period_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businesssubscription",
            name="past_due_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
