# Generated by Django 5.2.11 on 2026-07-18 23:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0019_businesssubscription_grace_period_ends_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("recipient_email", models.EmailField(blank=True, max_length=254)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("trial_started", "Trial Started"),
                            ("subscription_activated", "Subscription Activated"),
                            ("payment_grace_started", "Payment Grace Started"),
                            ("payment_recovered", "Payment Recovered"),
                            ("cancellation_scheduled", "Cancellation Scheduled"),
                            ("subscription_cancelled", "Subscription Cancelled"),
                            ("trial_ending_3_days", "Trial Ending in 3 Days"),
                            ("trial_ending_1_day", "Trial Ending in 1 Day"),
                            (
                                "payment_grace_ending_1_day",
                                "Payment Grace Ending in 1 Day",
                            ),
                            ("restricted_mode_started", "Restricted Mode Started"),
                        ],
                        max_length=40,
                    ),
                ),
                ("deduplication_key", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "available_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True, default="")),
                (
                    "source_provider_event_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("context_summary", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription_notifications",
                        to="businesses.business",
                    ),
                ),
                (
                    "recipient_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subscription_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="businesses.businesssubscription",
                    ),
                ),
            ],
            options={
                "ordering": ["available_at", "pk"],
                "indexes": [
                    models.Index(
                        fields=["status", "available_at"], name="businesses__status_ccf8e9_idx"
                    ),
                    models.Index(
                        fields=["business", "notification_type", "status"],
                        name="businesses__busines_20c5c8_idx",
                    ),
                    models.Index(
                        fields=["subscription", "notification_type"],
                        name="businesses__subscri_8e659f_idx",
                    ),
                ],
            },
        ),
    ]
