# Generated by Django 5.2.11 on 2026-09-05 13:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0020_subscriptionnotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessDataOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("operation_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("business_id_snapshot", models.PositiveBigIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("deactivate", "Deactivate"),
                            ("anonymize", "Anonymize"),
                            ("purge", "Purge"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("operator_id_snapshot", models.PositiveBigIntegerField(blank=True, null=True)),
                ("reason_reference", models.CharField(blank=True, default="", max_length=120)),
                ("record_counts", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=80)),
            ],
            options={
                "ordering": ["-started_at", "-pk"],
                "indexes": [
                    models.Index(
                        fields=["business_id_snapshot", "started_at"],
                        name="businesses__busines_4d388f_idx",
                    )
                ],
            },
        ),
    ]
