# Generated by Django 5.2.11 on 2026-09-27 20:03

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0021_business_data_operation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoSeedRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("planned_counts", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demo_seed_run",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["business_id"],
            },
        ),
        migrations.CreateModel(
            name="DemoSeedRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("model_label", models.CharField(max_length=100)),
                ("object_pk", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "seed_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_records",
                        to="businesses.demoseedrun",
                    ),
                ),
            ],
            options={
                "ordering": ["model_label", "object_pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("seed_run", "model_label", "object_pk"),
                        name="businesses_demo_seed_record_unique_target",
                    )
                ],
            },
        ),
    ]
