from django.urls import path

from .views import (
    agent_dashboard,
    business_service_archive,
    business_service_category_archive,
    business_service_category_create,
    business_service_category_list,
    business_service_category_update,
    business_service_create,
    business_service_import,
    business_service_import_execute,
    business_service_import_preview,
    business_service_import_result,
    business_service_list,
    business_service_sample_csv,
    business_service_update,
    client_detail_view,
    client_import_execute,
    client_import_preview,
    client_import_result,
    client_import_template,
    client_import_upload,
    # staff_lead_email,
    data_import,
    import_history,
    import_history_detail,
    lead_import_execute,
    lead_import_preview,
    lead_import_result,
    lead_import_template,
    lead_import_upload,
    public_request,
    public_request_entry,
    public_thank_you,
    staff_client_archive,
    staff_client_create,
    staff_client_detail,
    staff_client_list,
    staff_client_update,
    staff_lead_convert_to_client,
    staff_lead_create,
    staff_lead_create_invoice,
    staff_lead_detail,
    staff_lead_list,
    staff_lead_update,
)

urlpatterns = [
    path("agent/dashboard/", agent_dashboard, name="agent_dashboard"),
    path("staff/data-import/", data_import, name="data_import"),
    path("staff/data-import/history/", import_history, name="import_history"),
    path(
        "staff/data-import/history/<uuid:job_id>/",
        import_history_detail,
        name="import_history_detail",
    ),
    path("staff/data-import/clients/", client_import_upload, name="client_import_upload"),
    path(
        "staff/data-import/clients/template/",
        client_import_template,
        name="client_import_template",
    ),
    path(
        "staff/data-import/clients/<uuid:job_id>/preview/",
        client_import_preview,
        name="client_import_preview",
    ),
    path(
        "staff/data-import/clients/<uuid:job_id>/execute/",
        client_import_execute,
        name="client_import_execute",
    ),
    path(
        "staff/data-import/clients/<uuid:job_id>/result/",
        client_import_result,
        name="client_import_result",
    ),
    path("staff/data-import/leads/", lead_import_upload, name="lead_import_upload"),
    path(
        "staff/data-import/leads/template/",
        lead_import_template,
        name="lead_import_template",
    ),
    path(
        "staff/data-import/leads/<uuid:job_id>/preview/",
        lead_import_preview,
        name="lead_import_preview",
    ),
    path(
        "staff/data-import/leads/<uuid:job_id>/execute/",
        lead_import_execute,
        name="lead_import_execute",
    ),
    path(
        "staff/data-import/leads/<uuid:job_id>/result/",
        lead_import_result,
        name="lead_import_result",
    ),
    path("public_request/", public_request_entry, name="public_request_entry"),
    path("public_request/<slug:business_slug>/", public_request, name="public_request"),
    path("thanks/", public_thank_you, name="public_thank_you"),
    path("staff/leads/", staff_lead_list, name="staff_lead_list"),
    path("staff/leads/create/", staff_lead_create, name="staff_lead_create"),
    path("staff/leads/<int:lead_id>/edit/", staff_lead_update, name="staff_lead_update"),
    path(
        "staff/leads/<int:lead_id>/convert-to-client/",
        staff_lead_convert_to_client,
        name="staff_lead_convert_to_client",
    ),
    path(
        "staff/leads/<int:lead_id>/create-invoice/",
        staff_lead_create_invoice,
        name="staff_lead_create_invoice",
    ),
    path("staff/clients/create/", staff_client_create, name="staff_client_create"),
    path("staff/clients/", staff_client_list, name="staff_client_list"),
    path("staff/clients/<int:client_id>/edit/", staff_client_update, name="staff_client_update"),
    path("staff/clients/<int:client_id>/archive/", staff_client_archive, name="staff_client_archive"),
    path("staff/clients/<int:client_id>/", staff_client_detail, name="staff_client_detail"),
    path("staff/clients/all/", client_detail_view, name="client_detail_view"),

    path("staff/leads/<int:lead_id>/", staff_lead_detail, name="staff_lead_detail"),
    path(
        "settings/service-categories/",
        business_service_category_list,
        name="business_service_category_list",
    ),
    path(
        "settings/service-categories/create/",
        business_service_category_create,
        name="business_service_category_create",
    ),
    path(
        "settings/service-categories/<int:category_id>/edit/",
        business_service_category_update,
        name="business_service_category_update",
    ),
    path(
        "settings/service-categories/<int:category_id>/archive/",
        business_service_category_archive,
        name="business_service_category_archive",
    ),
    path(
        "settings/services/",
        business_service_list,
        name="business_service_list",
    ),
    path(
        "settings/services/create/",
        business_service_create,
        name="business_service_create",
    ),
    path(
        "settings/services/import/",
        business_service_import,
        name="business_service_import",
    ),
    path(
        "settings/services/import/<uuid:job_id>/preview/",
        business_service_import_preview,
        name="business_service_import_preview",
    ),
    path(
        "settings/services/import/<uuid:job_id>/execute/",
        business_service_import_execute,
        name="business_service_import_execute",
    ),
    path(
        "settings/services/import/<uuid:job_id>/result/",
        business_service_import_result,
        name="business_service_import_result",
    ),
    path(
        "settings/services/sample.csv",
        business_service_sample_csv,
        name="business_service_sample_csv",
    ),
    path(
        "settings/services/<int:service_id>/edit/",
        business_service_update,
        name="business_service_update",
    ),
    path(
        "settings/services/<int:service_id>/archive/",
        business_service_archive,
        name="business_service_archive",
    ),
    # path("staff/leads/<int:lead_id>/email/", staff_lead_email, name="staff_lead_email"),
]
