# Generated by Django 5.2.11 on 2026-06-21 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
        ("crm", "0009_businessservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="source_lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointments",
                to="crm.lead",
            ),
        ),
    ]
