# Generated by Django 5.2.11 on 2026-04-12 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invoice",
            name="lead",
        ),
    ]
