# Generated by Django 5.2.11 on 2026-05-15 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0002_remove_invoice_lead"),
        ("businesses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="businesses.business",
            ),
        ),
    ]
