# Generated by Django 5.2.11 on 2026-05-15 18:28

from collections import defaultdict

from django.db import migrations


def _get_legacy_business(Business, db_alias):
    existing_legacy_business = (
        Business.objects.using(db_alias)
        .filter(name="Legacy Workspace")
        .order_by("id")
        .first()
    )
    if existing_legacy_business:
        return existing_legacy_business

    base_slug = "legacy-workspace"
    slug = base_slug
    suffix = 2

    while Business.objects.using(db_alias).filter(slug=slug).exists():
        slug = f"{base_slug}-{suffix}"
        suffix += 1

    return Business.objects.using(db_alias).create(
        name="Legacy Workspace",
        slug=slug,
        is_active=True,
    )


def _get_fallback_business(Business, BusinessUser, db_alias):
    staff_business_id = (
        BusinessUser.objects.using(db_alias)
        .filter(
            is_active=True,
            business__is_active=True,
            role__in=("owner", "admin"),
            user__is_active=True,
            user__is_staff=True,
        )
        .order_by("business_id")
        .values_list("business_id", flat=True)
        .first()
    )

    if staff_business_id:
        return Business.objects.using(db_alias).get(pk=staff_business_id)

    return _get_legacy_business(Business, db_alias)


def backfill_existing_invoice_businesses(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Business = apps.get_model("businesses", "Business")
    BusinessUser = apps.get_model("businesses", "BusinessUser")
    Invoice = apps.get_model("billings", "Invoice")

    if not Invoice.objects.using(db_alias).filter(business__isnull=True).exists():
        return

    fallback_business = _get_fallback_business(Business, BusinessUser, db_alias)
    fallback_business_id = fallback_business.pk

    invoice_ids_by_business = defaultdict(list)
    invoices_without_business = (
        Invoice.objects.using(db_alias)
        .filter(business__isnull=True)
        .values_list("id", "client__business_id")
    )

    for invoice_id, client_business_id in invoices_without_business:
        business_id = client_business_id or fallback_business_id
        invoice_ids_by_business[business_id].append(invoice_id)

    for business_id, invoice_ids in invoice_ids_by_business.items():
        Invoice.objects.using(db_alias).filter(
            pk__in=invoice_ids,
            business__isnull=True,
        ).update(business_id=business_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_saasuserprofile"),
        ("billings", "0003_invoice_business"),
        ("businesses", "0001_initial"),
        ("crm", "0007_backfill_existing_crm_businesses"),
    ]

    operations = [
        migrations.RunPython(
            backfill_existing_invoice_businesses,
            migrations.RunPython.noop,
        ),
    ]
