# Generated by Django 5.2.11 on 2026-05-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0004_backfill_existing_invoice_businesses"),
        ("businesses", "0001_initial"),
        ("crm", "0007_backfill_existing_crm_businesses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name="invoice",
            constraint=models.UniqueConstraint(
                fields=("business", "invoice_number"),
                name="billings_invoice_unique_business_number",
            ),
        ),
    ]
