# Generated by Django 5.2.11 on 2026-05-15 19:04

import django.db.models.deletion
from django.db import migrations, models


def assert_no_null_invoice_businesses(apps, schema_editor):
    Invoice = apps.get_model("billings", "Invoice")
    db_alias = schema_editor.connection.alias

    null_count = Invoice.objects.using(db_alias).filter(business__isnull=True).count()
    if null_count:
        raise RuntimeError(
            "Cannot make Invoice.business required because "
            f"{null_count} invoice row(s) still have no business."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0005_alter_invoice_invoice_number_and_more"),
    ]

    operations = [
        migrations.RunPython(
            assert_no_null_invoice_businesses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoices",
                to="businesses.business",
            ),
        ),
    ]
