# Generated by Django 5.2.11 on 2026-05-21 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0006_invoice_business_required"),
        ("crm", "0009_businessservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoice_lines",
                to="crm.businessservice",
            ),
        ),
    ]
