# Generated by Django 5.2.11 on 2026-06-21 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_source_lead"),
        ("billings", "0007_invoiceline_service"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="appointments.appointment",
            ),
        ),
    ]
