# Generated by Django 5.2.11 on 2026-06-26 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0008_invoice_appointment"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="email_send_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="emailed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="emailed_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
