# Generated by Django 5.2.11 on 2026-10-07 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0009_invoice_email_send_count_invoice_emailed_at_and_more"),
        ("logistics", "0007_reconcile_parcel_handling_column"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoiceline",
            name="parcel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="logistics.parcel",
            ),
        ),
        migrations.AddField(
            model_name="invoiceline",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="invoice_lines",
                to="logistics.shipment",
            ),
        ),
    ]
