# Generated by Django 5.2.11 on 2026-03-04 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taskiouser",
            old_name="date_hired",
            new_name="date_operational",
        ),
        migrations.RemoveField(
            model_name="taskiouser",
            name="employment_status",
        ),
        migrations.RemoveField(
            model_name="taskiouser",
            name="role",
        ),
        migrations.AddField(
            model_name="taskiouser",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="taskiouser",
            name="incoporation_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="taskiouser",
            name="incorporation_status",
            field=models.CharField(
                choices=[
                    ("EMPLOYED", "Employed"),
                    ("UNEMPLOYED", "Unemployed"),
                    ("TERMINATED", "Terminated"),
                    ("RETIRED", "Retired"),
                    ("LEAVE_OF_ABSENCE", "Leave of Absence"),
                    ("INACTIVE", "Inactive"),
                ],
                default="CORPORATED",
                max_length=20,
            ),
        ),
    ]
