# Generated by Django 5.2.11 on 2026-03-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_rename_date_hired_taskiouser_date_operational_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskiouser",
            name="incorporation_status",
            field=models.CharField(
                choices=[("CORPORATED", "Corporated"), ("UNINCORPORATED", "Unincorporated")],
                default="CORPORATED",
                max_length=20,
            ),
        ),
    ]
