# Generated by Django 5.2.11 on 2026-04-11 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_taskiouser_incorporation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskiouser",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MANAGER", "Manager"),
                    ("AGENT", "Agent"),
                    ("CUSTOMER", "Customer"),
                ],
                default="AGENT",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("website", models.URLField(blank=True, null=True)),
                ("industry", models.CharField(blank=True, max_length=80, null=True)),
                ("phone", models.CharField(blank=True, max_length=30, null=True)),
                ("support_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("billing_email", models.EmailField(blank=True, max_length=254, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("default_currency", models.CharField(default="USD", max_length=10)),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                ("settings", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Company profile",
                "verbose_name_plural": "Company profiles",
            },
        ),
        migrations.AddField(
            model_name="taskiouser",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="accounts.companyprofile",
            ),
        ),
    ]
