# Generated by Django 5.2.11 on 2026-04-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_taskiouser_role_companyprofile_taskiouser_company"),
        ("crm", "0005_remove_client_company_remove_lead_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="taskiouser",
            name="company",
        ),
        migrations.RemoveField(
            model_name="taskiouser",
            name="role",
        ),
        migrations.DeleteModel(
            name="CompanyProfile",
        ),
    ]
