# Generated by Django 5.2.11 on 2026-04-12 00:00

import django.db.models.deletion
from django.conf import settings
from django.core.validators import MaxValueValidator, MinValueValidator, RegexValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_taskiouser_company_remove_taskiouser_role_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SaaSUserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("workspace_name", models.CharField(blank=True, max_length=120)),
                ("billing_email", models.EmailField(blank=True, max_length=254)),
                ("support_email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("tax_id", models.CharField(blank=True, max_length=60)),
                (
                    "currency_code",
                    models.CharField(
                        choices=[
                            ("USD", "US Dollar (USD)"),
                            ("XCD", "East Caribbean Dollar (XCD)"),
                            ("EUR", "Euro (EUR)"),
                            ("ANG", "Netherlands Antillean Guilder (ANG)"),
                        ],
                        default="USD",
                        max_length=3,
                    ),
                ),
                (
                    "invoice_prefix",
                    models.CharField(
                        default="INV",
                        max_length=12,
                        validators=[
                            RegexValidator(
                                message="Use 2-12 uppercase letters, numbers, or hyphens for the invoice prefix.",
                                regex="^[A-Z0-9-]{2,12}$",
                            )
                        ],
                    ),
                ),
                (
                    "invoice_default_due_days",
                    models.PositiveSmallIntegerField(
                        default=14,
                        validators=[MinValueValidator(1), MaxValueValidator(90)],
                    ),
                ),
                (
                    "invoice_accent_color",
                    models.CharField(
                        default="#2C7BE5",
                        max_length=7,
                        validators=[
                            RegexValidator(
                                message="Enter a valid hex color such as #2C7BE5.",
                                regex="^#[0-9A-Fa-f]{6}$",
                            )
                        ],
                    ),
                ),
                ("show_company_address_on_invoice", models.BooleanField(default=True)),
                ("show_tax_id_on_invoice", models.BooleanField(default=True)),
                ("payment_instructions", models.TextField(blank=True)),
                ("invoice_footer_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saas_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "SaaS User Profile",
                "verbose_name_plural": "SaaS User Profiles",
            },
        ),
    ]
