# Generated by Django 5.2.11 on 2026-10-04 19:50

import uuid

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsApplication",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "business_name",
                    models.CharField(max_length=120, verbose_name="Legal / business name"),
                ),
                ("trading_name", models.CharField(blank=True, max_length=120)),
                ("contact_first_name", models.CharField(max_length=100)),
                ("contact_last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "phone",
                    models.CharField(
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[+()\\d .-]+$", "Enter a valid phone number."
                            )
                        ],
                    ),
                ),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        max_length=30,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[+()\\d .-]+$", "Enter a valid phone number."
                            )
                        ],
                        verbose_name="WhatsApp number",
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Country / territory")),
                (
                    "business_address",
                    models.TextField(
                        max_length=1000,
                        validators=[django.core.validators.MaxLengthValidator(1000)],
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Registration / company number"
                    ),
                ),
                ("website", models.URLField(blank=True)),
                (
                    "preferred_currency",
                    models.CharField(
                        choices=[("USD", "US dollar (USD)"), ("EUR", "Euro (EUR)")], max_length=3
                    ),
                ),
                ("timezone", models.CharField(default="UTC", max_length=100)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("COURIER", "Courier / local parcel delivery"),
                            ("FORWARDER", "Parcel / freight forwarding"),
                            ("COLLECTION", "Parcel collection / distribution"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "routes",
                    models.TextField(
                        max_length=3000,
                        validators=[django.core.validators.MaxLengthValidator(3000)],
                        verbose_name="Origins, destinations and routes",
                    ),
                ),
                (
                    "monthly_parcel_estimate",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "expected_staff_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "location_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Location / branch count",
                    ),
                ),
                (
                    "current_process_method",
                    models.CharField(
                        choices=[
                            ("PAPER", "Paper / manual records"),
                            ("SPREADSHEETS", "Spreadsheets"),
                            ("MESSAGING", "WhatsApp / messaging"),
                            ("SOFTWARE", "Tracking software"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "current_process_details",
                    models.TextField(
                        blank=True,
                        max_length=3000,
                        validators=[django.core.validators.MaxLengthValidator(3000)],
                    ),
                ),
                ("customer_tracking_needed", models.BooleanField(default=False)),
                ("manifest_needed", models.BooleanField(default=False)),
                ("api_integration_needed", models.BooleanField(default=False)),
                ("custom_workflow", models.BooleanField(default=False)),
                (
                    "custom_workflow_details",
                    models.TextField(
                        blank=True,
                        max_length=3000,
                        validators=[django.core.validators.MaxLengthValidator(3000)],
                    ),
                ),
                ("multi_jurisdiction", models.BooleanField(default=False)),
                (
                    "custom_pricing_requested",
                    models.BooleanField(
                        default=False, verbose_name="Enterprise / custom pricing requested"
                    ),
                ),
                (
                    "operational_notes",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        validators=[django.core.validators.MaxLengthValidator(5000)],
                    ),
                ),
                (
                    "normalized_email",
                    models.CharField(db_index=True, editable=False, max_length=254),
                ),
                (
                    "normalized_business_name",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                (
                    "normalized_registration_number",
                    models.CharField(blank=True, db_index=True, editable=False, max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("UNDER_REVIEW", "Under review"),
                            ("DECLINED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        db_index=True,
                        default="SUBMITTED",
                        max_length=20,
                    ),
                ),
                ("revision", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "approved_revision",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("decision_result", models.CharField(blank=True, editable=False, max_length=20)),
                ("reason_codes", models.JSONField(blank=True, default=list, editable=False)),
                ("evaluated_at", models.DateTimeField(blank=True, editable=False, null=True)),
                (
                    "evaluated_revision",
                    models.PositiveIntegerField(blank=True, editable=False, null=True),
                ),
                ("rule_version", models.CharField(blank=True, editable=False, max_length=100)),
                ("threshold_snapshot", models.JSONField(blank=True, default=dict, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LogisticsApplicationDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("application_revision", models.PositiveIntegerField()),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("UNDER_REVIEW", "Under review"),
                            ("DECLINED", "Declined"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        max_length=20,
                    ),
                ),
                ("evaluated_result", models.CharField(max_length=20)),
                ("reason_codes", models.JSONField(default=list)),
                ("evaluated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("rule_version", models.CharField(max_length=100)),
                ("threshold_snapshot", models.JSONField()),
                ("evaluated_inputs", models.JSONField()),
                ("relationship_snapshot", models.JSONField()),
                ("resource_classification", models.CharField(max_length=30)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("AUTOMATIC", "Automatic evaluation"),
                            ("MANUAL", "Manual review"),
                        ],
                        max_length=20,
                    ),
                ),
                ("actor_identifier", models.PositiveBigIntegerField(blank=True, null=True)),
                ("override_reason", models.TextField(blank=True, max_length=3000)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_application_decisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="decisions",
                        to="logistics.logisticsapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-evaluated_at", "-pk"],
            },
        ),
    ]
