# Generated by Django 5.2.11 on 2026-10-04 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0026_logistics_offering"),
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsapplication",
            name="business",
            field=models.OneToOneField(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logistics_application",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="logisticsapplication",
            name="converted_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="logisticsapplication",
            name="converted_revision",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="logisticsapplication",
            name="enrolled_user",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="logistics_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="LogisticsEnrollmentToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token_digest", models.CharField(editable=False, max_length=64, unique=True)),
                ("application_revision", models.PositiveIntegerField(editable=False)),
                ("expires_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollment_tokens",
                        to="logistics.logisticsapplication",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_logistics_enrollments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="logisticsapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", True),
                        ("converted_at__isnull", True),
                        ("converted_revision__isnull", True),
                        ("enrolled_user__isnull", True),
                    ),
                    models.Q(
                        ("business__isnull", False),
                        ("converted_at__isnull", False),
                        ("converted_revision__isnull", False),
                        ("enrolled_user__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="logistics_conversion_complete_or_absent",
            ),
        ),
    ]
