# Generated by Django 5.2.11 on 2026-10-04 21:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import apps.logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0026_logistics_offering"),
        ("crm", "0016_merge_import_preview_and_client_status"),
        ("logistics", "0002_logisticsapplication_business_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parcel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        default=apps.logistics.models.generate_tracking_code,
                        editable=False,
                        max_length=48,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("\\A[A-F0-9]{48}\\Z")],
                    ),
                ),
                ("internal_reference", models.CharField(blank=True, max_length=100)),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("package_description", models.CharField(max_length=1000)),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1, validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Optional dimensions, including units.",
                        max_length=100,
                    ),
                ),
                (
                    "declared_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("RECEIVED", "Received"),
                            ("IN_TRANSIT", "In transit"),
                            ("ARRIVED", "Arrived"),
                            ("READY", "Ready for collection / delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("HOLD", "On hold"),
                        ],
                        default="REGISTERED",
                        editable=False,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcels",
                        to="businesses.business",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcels",
                        to="crm.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="registered_parcels",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="ParcelEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("STATUS", "Status change"), ("NOTE", "Tracking update")],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REGISTERED", "Registered"),
                            ("RECEIVED", "Received"),
                            ("IN_TRANSIT", "In transit"),
                            ("ARRIVED", "Arrived"),
                            ("READY", "Ready for collection / delivery"),
                            ("DELIVERED", "Delivered"),
                            ("CANCELLED", "Cancelled"),
                            ("HOLD", "On hold"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("public_message", models.CharField(blank=True, max_length=1000)),
                ("internal_note", models.CharField(blank=True, max_length=2000)),
                ("idempotency_key", models.UUIDField(blank=True, editable=False, null=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="parcel_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parcel_events",
                        to="businesses.business",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="logistics.parcel",
                    ),
                ),
            ],
            options={
                "ordering": ["timestamp", "pk"],
            },
        ),
        migrations.AddIndex(
            model_name="parcel",
            index=models.Index(
                fields=["business", "current_status", "created_at"],
                name="logistics_p_busines_5f77c0_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcel",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="parcel_quantity_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="parcel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("weight_kg__isnull", True), ("weight_kg__gte", 0), _connector="OR"
                ),
                name="parcel_weight_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("declared_value__isnull", True), ("declared_value__gte", 0), _connector="OR"
                ),
                name="parcel_value_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="parcel",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "current_status__in",
                        [
                            "REGISTERED",
                            "RECEIVED",
                            "IN_TRANSIT",
                            "ARRIVED",
                            "READY",
                            "DELIVERED",
                            "CANCELLED",
                            "HOLD",
                        ],
                    )
                ),
                name="parcel_status_known",
            ),
        ),
        migrations.AddIndex(
            model_name="parcelevent",
            index=models.Index(
                fields=["business", "parcel", "timestamp"], name="logistics_p_busines_b427a0_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="parcelevent",
            constraint=models.UniqueConstraint(
                fields=("business", "idempotency_key"), name="parcel_event_retry_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="parcelevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("event_type", "NOTE"), ("status", "")),
                    models.Q(
                        ("event_type", "STATUS"),
                        (
                            "status__in",
                            [
                                "REGISTERED",
                                "RECEIVED",
                                "IN_TRANSIT",
                                "ARRIVED",
                                "READY",
                                "DELIVERED",
                                "CANCELLED",
                                "HOLD",
                            ],
                        ),
                    ),
                    _connector="OR",
                ),
                name="parcel_event_status_consistent",
            ),
        ),
    ]
