# Generated by Django 5.2.11 on 2026-10-04 22:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.logistics.models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0026_logistics_offering"),
        ("logistics", "0003_parcel_parcelevent_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        default=apps.logistics.models.generate_shipment_reference,
                        editable=False,
                        max_length=36,
                        unique=True,
                    ),
                ),
                ("origin", models.CharField(max_length=255)),
                ("destination", models.CharField(max_length=255)),
                ("departure_at", models.DateTimeField(blank=True, null=True)),
                ("estimated_arrival_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("READY", "Ready"),
                            ("IN_TRANSIT", "In transit"),
                            ("ARRIVED", "Arrived"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        editable=False,
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        max_length=2000,
                        validators=[django.core.validators.MaxLengthValidator(2000)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="shipments",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_shipments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="parcel",
            name="shipment",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parcels",
                to="logistics.shipment",
            ),
        ),
        migrations.AddIndex(
            model_name="shipment",
            index=models.Index(
                fields=["business", "status", "created_at"], name="logistics_s_busines_ecdc85_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["DRAFT", "READY", "IN_TRANSIT", "ARRIVED", "COMPLETED", "CANCELLED"],
                    )
                ),
                name="shipment_status_known",
            ),
        ),
    ]
