# Generated by Django 5.2.11 on 2026-10-05 00:15

from django.conf import settings
from django.db import migrations, models


def backfill_business_snapshot(apps, schema_editor):
    Application = apps.get_model("logistics", "LogisticsApplication")
    Application.objects.using(schema_editor.connection.alias).filter(business__isnull=False).update(
        business_id_snapshot=models.F("business_id")
    )


def protect_retained_history(apps, schema_editor):
    Application = apps.get_model("logistics", "LogisticsApplication")
    if (
        Application.objects.using(schema_editor.connection.alias)
        .filter(business__isnull=True, converted_at__isnull=False)
        .exists()
    ):
        raise RuntimeError(
            "Cannot remove conversion snapshots after tenant purge; retained history must survive."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0026_logistics_offering"),
        ("logistics", "0004_shipment_parcel_shipment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="logisticsapplication",
            name="logistics_conversion_complete_or_absent",
        ),
        migrations.AddField(
            model_name="logisticsapplication",
            name="business_id_snapshot",
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(backfill_business_snapshot, protect_retained_history),
        migrations.AddConstraint(
            model_name="logisticsapplication",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("business__isnull", True),
                        ("business_id_snapshot__isnull", True),
                        ("converted_at__isnull", True),
                        ("converted_revision__isnull", True),
                        ("enrolled_user__isnull", True),
                    ),
                    models.Q(
                        ("converted_at__isnull", False),
                        ("converted_revision__isnull", False),
                        ("enrolled_user__isnull", False),
                        models.Q(
                            ("business__isnull", False),
                            ("business_id_snapshot__isnull", False),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="logistics_conversion_complete_or_absent",
            ),
        ),
    ]
