# Generated by Django 5.2.11 on 2026-10-06 20:37

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_application_purge_retention"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="fragile_goods",
            field=models.BooleanField(default=False, verbose_name="Fragile goods"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Height (cm)",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="house_bl_no",
            field=models.CharField(blank=True, max_length=100, verbose_name="House bill of lading"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="hs_code",
            field=models.CharField(blank=True, max_length=100, verbose_name="HS code"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="imo_no",
            field=models.CharField(blank=True, max_length=100, verbose_name="IMO number"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="incoterms",
            field=models.CharField(blank=True, max_length=100, verbose_name="Incoterms"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="internal_notes",
            field=models.CharField(blank=True, max_length=2000, verbose_name="Internal notes"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="issue_date",
            field=models.DateField(blank=True, null=True, verbose_name="Document issue date"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="length_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Length (cm)",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="marks_numbers",
            field=models.CharField(blank=True, max_length=100, verbose_name="Marks and numbers"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="master_bl_no",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Master bill of lading"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="mode_of_transport",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="parcel",
            name="biodegradable_goods",
            field=models.BooleanField(default=False, verbose_name="Biodegradable goods"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="port_discharge_unlocode",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Discharge port (UN/LOCODE)"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="port_load_unlocode",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Loading port (UN/LOCODE)"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_address",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_address",
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_contact",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_country_code",
            field=models.CharField(
                blank=True,
                max_length=3,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\A[A-Za-z]{2,3}\\Z", "Use a two or three letter country code."
                    )
                ],
                verbose_name="Sender country code",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_tax_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="Sender tax ID"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="vessel_name",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Vessel / carrier name"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="volume_m3",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Volume (m³)",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="voyage_no",
            field=models.CharField(blank=True, max_length=100, verbose_name="Voyage number"),
        ),
        migrations.AddField(
            model_name="parcel",
            name="width_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Width (cm)",
            ),
        ),
    ]
