# Generated by Django 5.2.11 on 2026-10-07 05:17

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billings", "0010_invoiceline_parcel_invoiceline_shipment"),
        ("businesses", "0026_logistics_offering"),
        ("crm", "0016_merge_import_preview_and_client_status"),
        ("logistics", "0007_reconcile_parcel_handling_column"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LogisticsCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("target_reference", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=160)),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("idempotency_key", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_charges",
                        to="businesses.business",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_charges",
                        to="crm.client",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logistics_charges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invoice_line",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_charge",
                        to="billings.invoiceline",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="logistics.parcel",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_charges",
                        to="crm.businessservice",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charges",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("parcel__isnull", False), ("shipment__isnull", True)),
                            models.Q(("parcel__isnull", True), ("shipment__isnull", False)),
                            _connector="OR",
                        ),
                        name="logistics_charge_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gt", 0), ("unit_price__gte", 0)),
                        name="logistics_charge_positive_amounts",
                    ),
                    models.UniqueConstraint(
                        fields=("business", "idempotency_key"), name="logistics_charge_retry_unique"
                    ),
                ],
            },
        ),
    ]
