# Generated by Django 5.2.11 on 2026-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0008_logisticscharge"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="idempotency_key",
            field=models.UUIDField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="shipment",
            name="revision",
            field=models.PositiveBigIntegerField(default=1, editable=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="write_receipts",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.UniqueConstraint(
                fields=("business", "idempotency_key"), name="shipment_creation_retry_unique"
            ),
        ),
    ]
