# Generated by Django 5.2.11 on 2026-10-07 22:20

import django.db.models.deletion
from django.db import migrations, models

import apps.logistics.classification


def backfill_logistics_profiles(apps, schema_editor):
    Business = apps.get_model("businesses", "Business")
    Profile = apps.get_model("logistics", "LogisticsProfile")
    alias = schema_editor.connection.alias
    for business_id in (
        Business.objects.using(alias)
        .filter(vertical="LOGISTICS")
        .values_list("pk", flat=True)
        .iterator()
    ):
        Profile.objects.using(alias).get_or_create(
            business_id=business_id,
            defaults={"operating_areas": ["TRANSPORTATION"], "transportation_modes": []},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0027_businesssubscription_logistics_approval_review_required"),
        ("logistics", "0009_shipment_write_safety"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsapplication",
            name="operating_areas",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.logistics.classification.validate_operating_areas],
            ),
        ),
        migrations.AddField(
            model_name="logisticsapplication",
            name="transportation_modes",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[apps.logistics.classification.validate_transportation_modes],
            ),
        ),
        migrations.CreateModel(
            name="LogisticsProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "operating_areas",
                    models.JSONField(
                        blank=True,
                        default=apps.logistics.classification.default_operating_areas,
                        validators=[apps.logistics.classification.validate_operating_areas],
                    ),
                ),
                (
                    "transportation_modes",
                    models.JSONField(
                        blank=True,
                        default=list,
                        validators=[apps.logistics.classification.validate_transportation_modes],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_profile",
                        to="businesses.business",
                    ),
                ),
            ],
            bases=(apps.logistics.classification.ClassificationHelpers, models.Model),
        ),
        migrations.RunPython(backfill_logistics_profiles, migrations.RunPython.noop),
    ]
