# Generated by Django 5.2.11 on 2026-10-08 00:07

from django.conf import settings
from django.db import migrations, models


def backfill_transport_mode(apps, schema_editor):
    Profile = apps.get_model("logistics", "LogisticsProfile")
    Shipment = apps.get_model("logistics", "Shipment")
    alias = schema_editor.connection.alias
    # Freeze the migration's accepted taxonomy; runtime choices may evolve later.
    known_modes = {value for value, _ in Shipment._meta.get_field("transport_mode").choices}
    for profile in Profile.objects.using(alias).filter(business__vertical="LOGISTICS").iterator():
        modes = profile.transportation_modes
        if (
            isinstance(modes, list)
            and len(modes) == 1
            and isinstance(modes[0], str)
            and modes[0] in known_modes
        ):
            Shipment.objects.using(alias).filter(
                business_id=profile.business_id, transport_mode__isnull=True
            ).update(transport_mode=modes[0])


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0027_businesssubscription_logistics_approval_review_required"),
        ("logistics", "0010_operating_classification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="transport_mode",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SEA", "Sea"),
                    ("AIR", "Air"),
                    ("ROAD", "Road / Truck"),
                    ("RAIL", "Rail"),
                ],
                max_length=4,
                null=True,
                verbose_name="Transportation mode",
            ),
        ),
        migrations.RunPython(backfill_transport_mode, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="shipment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("transport_mode__isnull", True),
                    ("transport_mode__in", ["SEA", "AIR", "ROAD", "RAIL"]),
                    _connector="OR",
                ),
                name="shipment_transport_mode_known",
            ),
        ),
    ]
