# Generated by Django 5.2.11 on 2026-10-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0011_shipment_transport_mode"),
    ]

    operations = [
        migrations.AddField(
            model_name="shipment",
            name="bill_of_lading_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Bill of Lading"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="carrier_name",
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name="Carrier"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="container_reference",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Container"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="dispatch_reference",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dispatch Reference"
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="driver_name",
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name="Driver"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vehicle_reference",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Vehicle"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="vessel_name",
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name="Vessel"),
        ),
        migrations.AddField(
            model_name="shipment",
            name="voyage_reference",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Voyage"),
        ),
    ]
