# Generated by Django 5.2.11 on 2026-10-10 15:49

import apps.logistics.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0012_shipment_transport_references"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parcel",
            name="tracking_code",
            field=models.CharField(
                default=apps.logistics.models.generate_tracking_code,
                editable=False,
                max_length=48,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "\\A(?:[A-F0-9]{48}|MM-PCL-[A-HJKM-NP-Z2-9]{39})\\Z"
                    )
                ],
            ),
        ),
    ]
