# Generated by Django 5.2.11 on 2026-10-10 16:19

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models

import apps.logistics.location_reference


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0027_businesssubscription_logistics_approval_review_required"),
        ("logistics", "0013_tracking_code_v2"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsapplication",
            name="country_code",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=2,
                null=True,
                validators=[apps.logistics.location_reference.validate_country_code],
            ),
        ),
        migrations.AddField(
            model_name="logisticsapplication",
            name="location_review_required",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="destination_country_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.country_choices,
                max_length=2,
                null=True,
                validators=[apps.logistics.location_reference.validate_country_code],
                verbose_name="Destination country / territory",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="destination_reference_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.reference_choices,
                max_length=5,
                validators=[apps.logistics.location_reference.validate_reference_code],
                verbose_name="Destination port / airport reference",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="location_review_required",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="parcel",
            name="origin_country_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.country_choices,
                max_length=2,
                null=True,
                validators=[apps.logistics.location_reference.validate_country_code],
                verbose_name="Origin country / territory",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="origin_reference_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.reference_choices,
                max_length=5,
                validators=[apps.logistics.location_reference.validate_reference_code],
                verbose_name="Origin port / airport reference",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_country_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.country_choices,
                max_length=2,
                null=True,
                validators=[apps.logistics.location_reference.validate_country_code],
                verbose_name="Destination country / territory",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_reference_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.reference_choices,
                max_length=5,
                validators=[apps.logistics.location_reference.validate_reference_code],
                verbose_name="Destination port / airport reference",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="location_review_required",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_country_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.country_choices,
                max_length=2,
                null=True,
                validators=[apps.logistics.location_reference.validate_country_code],
                verbose_name="Origin country / territory",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_reference_code",
            field=models.CharField(
                blank=True,
                choices=apps.logistics.location_reference.reference_choices,
                max_length=5,
                validators=[apps.logistics.location_reference.validate_reference_code],
                verbose_name="Origin port / airport reference",
            ),
        ),
        migrations.CreateModel(
            name="LogisticsLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=160, verbose_name="Canonical name")),
                (
                    "code",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "\\A[A-Za-z][A-Za-z0-9-]{1,19}\\Z",
                                "Use 2–20 letters, numbers or hyphens, starting with a letter.",
                            )
                        ],
                        verbose_name="Stable short code",
                    ),
                ),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("PORT", "Port"),
                            ("AIRPORT", "Airport"),
                            ("WAREHOUSE", "Warehouse"),
                            ("BRANCH", "Branch"),
                            ("HUB", "Hub"),
                            ("PICKUP_POINT", "Pickup point"),
                            ("OTHER", "Other"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        choices=apps.logistics.location_reference.country_choices,
                        max_length=2,
                        validators=[apps.logistics.location_reference.validate_country_code],
                        verbose_name="Country / territory",
                    ),
                ),
                (
                    "reference_code",
                    models.CharField(
                        blank=True,
                        choices=apps.logistics.location_reference.reference_choices,
                        max_length=5,
                        validators=[apps.logistics.location_reference.validate_reference_code],
                        verbose_name="Verified port / airport reference",
                    ),
                ),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=120)),
                ("region", models.CharField(blank=True, max_length=120)),
                ("postal_code", models.CharField(blank=True, max_length=40)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_locations",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
            },
        ),
        migrations.AddField(
            model_name="parcel",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_destinations",
                to="logistics.logisticslocation",
                verbose_name="Destination company facility",
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origins",
                to="logistics.logisticslocation",
                verbose_name="Origin company facility",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_destinations",
                to="logistics.logisticslocation",
                verbose_name="Destination company facility",
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="origin_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_origins",
                to="logistics.logisticslocation",
                verbose_name="Origin company facility",
            ),
        ),
        migrations.AddConstraint(
            model_name="logisticslocation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("code"),
                models.F("business"),
                name="logistics_location_code_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="logisticslocation",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("business"),
                name="logistics_location_name_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="logisticslocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "location_type__in",
                        ["PORT", "AIRPORT", "WAREHOUSE", "BRANCH", "HUB", "PICKUP_POINT", "OTHER"],
                    )
                ),
                name="logistics_location_type_known",
            ),
        ),
    ]
