# Generated by Django 5.2.11 on 2026-10-10 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0027_businesssubscription_logistics_approval_review_required"),
        ("logistics", "0015_backfill_verified_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticsprofile",
            name="location_access_reviewed_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name="LogisticsHandlingSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("EXPECTED", "Expected at site"),
                            ("CURRENT", "Currently handled at site"),
                            ("STOP", "Operational stop"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_handling_sites",
                        to="businesses.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="handling_sites",
                        to="logistics.logisticslocation",
                    ),
                ),
                (
                    "parcel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_sites",
                        to="logistics.parcel",
                    ),
                ),
                (
                    "shipment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="handling_sites",
                        to="logistics.shipment",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("parcel__isnull", False), ("shipment__isnull", True)),
                            models.Q(("parcel__isnull", True), ("shipment__isnull", False)),
                            _connector="OR",
                        ),
                        name="logistics_handling_one_target",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("kind__in", ["EXPECTED", "CURRENT", "STOP"])),
                        name="logistics_handling_kind_known",
                    ),
                    models.UniqueConstraint(
                        fields=("parcel", "location", "kind"), name="logistics_parcel_site_unique"
                    ),
                    models.UniqueConstraint(
                        fields=("shipment", "location", "kind"),
                        name="logistics_shipment_site_unique",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LogisticsLocationAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("can_operate", models.BooleanField(default=False)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="logistics_location_assignments",
                        to="businesses.business",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worker_assignments",
                        to="logistics.logisticslocation",
                    ),
                ),
                (
                    "membership",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logistics_location_assignments",
                        to="businesses.businessuser",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("membership", "location"), name="logistics_worker_location_unique"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("membership",),
                        name="logistics_worker_current_unique",
                    ),
                ],
            },
        ),
    ]
