# Generated by Django 5.2.11 on 2026-10-10 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0016_worker_location_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="logisticslocationassignment",
            name="is_work_context",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="logisticsprofile",
            name="location_operations_enabled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="parcelevent",
            name="location_override_reason",
            field=models.CharField(blank=True, editable=False, max_length=1000),
        ),
        migrations.AddField(
            model_name="parcelevent",
            name="operational_location",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="parcel_events",
                to="logistics.logisticslocation",
            ),
        ),
        migrations.AddField(
            model_name="parcelevent",
            name="previous_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGISTERED", "Registered"),
                    ("RECEIVED", "Received"),
                    ("IN_TRANSIT", "In transit"),
                    ("ARRIVED", "Arrived"),
                    ("READY", "Ready for collection / delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("HOLD", "On hold"),
                ],
                editable=False,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="parcelevent",
            name="resulting_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REGISTERED", "Registered"),
                    ("RECEIVED", "Received"),
                    ("IN_TRANSIT", "In transit"),
                    ("ARRIVED", "Arrived"),
                    ("READY", "Ready for collection / delivery"),
                    ("DELIVERED", "Delivered"),
                    ("CANCELLED", "Cancelled"),
                    ("HOLD", "On hold"),
                ],
                editable=False,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shipment",
            name="operation_history",
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
    ]
