# Generated by Django 5.2.11 on 2026-10-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0017_verified_operations"),
    ]

    operations = [
        migrations.AddField(
            model_name="parcel",
            name="recipient_address_line_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Recipient address line 1"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Recipient address line 2"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_country_code",
            field=models.CharField(
                blank=True, max_length=2, null=True, verbose_name="Recipient country / territory"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_postal_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="recipient_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_address_line_1",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sender address line 1"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_address_line_2",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Sender address line 2"
            ),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_postal_code",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name="parcel",
            name="sender_region",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
