# Generated by Django 5.2.11 on 2026-02-24 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("company_name", models.CharField(blank=True, max_length=120)),
                ("message", models.TextField(blank=True)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MIDDLEREGION", "Middle Region"),
                            ("DUTCH_QUARTER", "Dutch Quarter"),
                            ("MADAMEESTATE", "Madame Estate"),
                            ("UNIONFARM", "Union Farm"),
                            ("OYSTERPOND", "Oyster Pond"),
                            ("DEFIANCE", "Defiance"),
                            ("SUCKERGARDEN", "Sucker Garden"),
                            ("HOPE_ESTATE", "Hope Estate"),
                            ("POINT_BLANCHE", "Point Blanche"),
                            ("GUANA_BAY", "Guana Bay"),
                            ("ST_PETERS", "St. Peters"),
                            ("SOUTH_REWARD", "South Reward"),
                            ("ST_JOHN", "St. John"),
                            ("EBENEZER", "Ebenezer"),
                            ("SAUNDERS", "Saunders"),
                            ("MARYS_FANCY", "Mary's Fancy"),
                            ("PHILIPSBURG", "Philipsburg"),
                            ("BELAIR", "Belair"),
                            ("INDIGO_BAY", "Indigo Bay"),
                            ("COLE_BAY", "Cole Bay"),
                            ("PELICAN_KEY", "Pelican Key"),
                            ("SIMPSON_BAY", "Simpson Bay"),
                            ("MAHO", "Maho"),
                        ],
                        max_length=100,
                    ),
                ),
                ("state", models.CharField(blank=True, default="Sint Maarten", max_length=100)),
                ("postal_code", models.CharField(blank=True, default="00000", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("consent_to_contact", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["first_name", "last_name"],
            },
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("REQUEST", "Service Request"),
                            ("INTEREST", "Interested (no request yet)"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("NEW", "New"),
                            ("CONTACTED", "Contacted"),
                            ("INVOICED", "Invoiced"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="NEW",
                        max_length=20,
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(blank=True, max_length=80)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("company_name", models.CharField(max_length=120)),
                ("message", models.TextField(blank=True)),
                ("street_address", models.CharField(blank=True, max_length=255)),
                (
                    "district",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MIDDLEREGION", "Middle Region"),
                            ("DUTCH_QUARTER", "Dutch Quarter"),
                            ("MADAMEESTATE", "Madame Estate"),
                            ("UNIONFARM", "Union Farm"),
                            ("OYSTERPOND", "Oyster Pond"),
                            ("DEFIANCE", "Defiance"),
                            ("SUCKERGARDEN", "Sucker Garden"),
                            ("HOPE_ESTATE", "Hope Estate"),
                            ("POINT_BLANCHE", "Point Blanche"),
                            ("GUANA_BAY", "Guana Bay"),
                            ("ST_PETERS", "St. Peters"),
                            ("SOUTH_REWARD", "South Reward"),
                            ("ST_JOHN", "St. John"),
                            ("EBENEZER", "Ebenezer"),
                            ("SAUNDERS", "Saunders"),
                            ("MARYS_FANCY", "Mary's Fancy"),
                            ("PHILIPSBURG", "Philipsburg"),
                            ("BELAIR", "Belair"),
                            ("INDIGO_BAY", "Indigo Bay"),
                            ("COLE_BAY", "Cole Bay"),
                            ("PELICAN_KEY", "Pelican Key"),
                            ("SIMPSON_BAY", "Simpson Bay"),
                            ("MAHO", "Maho"),
                        ],
                        max_length=100,
                    ),
                ),
                ("country", models.CharField(blank=True, default="Sint Maarten", max_length=100)),
                ("postal_code", models.CharField(blank=True, default="N/A", max_length=20)),
                ("notes", models.TextField(blank=True)),
                ("consent_to_contact", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ServiceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("SEPTIC_PUMPING", "Septic Pumping"),
                            ("SEPTIC_INSTALLATION", "Septic Installation"),
                            ("SEPTIC_REPAIR", "Septic Repair"),
                            ("GREASE_TRAP_SERVICES", "Grease Trap Services"),
                            ("UNCLOGGING_SERVICES", "Unclogging Services"),
                            ("OTHER", "Other"),
                        ],
                        max_length=60,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("EMAIL_SENT", "Email Sent"),
                            ("INVOICE_CREATED", "Invoice Created"),
                            ("STATUS_CHANGED", "Status Changed"),
                        ],
                        max_length=40,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=255)),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="crm.client",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="crm.servicecategory",
            ),
        ),
        migrations.AddIndex(
            model_name="lead",
            index=models.Index(fields=["status", "created_at"], name="crm_lead_status_18283c_idx"),
        ),
    ]
