# Generated by Django 5.2.11 on 2026-03-05 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_seed_service_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="assigned_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_clients",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="business_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="business_legal_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="client",
            name="client_status",
            field=models.CharField(
                choices=[
                    ("LEAD", "Lead"),
                    ("PROSPECT", "Prospect"),
                    ("ACTIVE", "Active Client"),
                    ("INACTIVE", "Inactive"),
                    ("ARCHIVED", "Archived"),
                ],
                default="LEAD",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="client_type",
            field=models.CharField(
                choices=[("INDIVIDUAL", "Individual"), ("BUSINESS", "Business")],
                default="BUSINESS",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="communication_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="interested_services",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="job_title",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="last_contacted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEBSITE", "Website"),
                    ("REFERRAL", "Referral"),
                    ("WALK_IN", "Walk-in"),
                    ("INSTAGRAM", "Instagram"),
                    ("FACEBOOK", "Facebook"),
                    ("LINKEDIN", "LinkedIn"),
                    ("PHONE", "Phone Inquiry"),
                    ("OTHER", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="next_follow_up_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="preferred_contact_method",
            field=models.CharField(
                choices=[("EMAIL", "Email"), ("PHONE", "Phone"), ("WHATSAPP", "WhatsApp")],
                default="EMAIL",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="preferred_language",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="client",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "Low"), ("MEDIUM", "Medium"), ("HIGH", "High")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="registration_number",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="client",
            name="secondary_phone",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="client",
            name="trade_name",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="client",
            name="website",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
