# Generated by Django 5.2.11 on 2026-04-11 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_taskiouser_role_companyprofile_taskiouser_company"),
        ("crm", "0003_client_assigned_to_client_business_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="accounts.companyprofile",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="accounts.companyprofile",
            ),
        ),
    ]
