# Generated by Django 5.2.11 on 2026-04-11 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0004_client_company_lead_company"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="company",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="company",
        ),
    ]
