# Generated by Django 5.2.11 on 2026-05-14 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("crm", "0005_remove_client_company_remove_lead_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="activitylog",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_logs",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clients",
                to="businesses.business",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="businesses.business",
            ),
        ),
    ]
