# Generated by Django 5.2.11 on 2026-05-14 21:02

from collections import defaultdict

from django.db import migrations


def _build_user_business_map(BusinessUser, db_alias):
    user_business_map = {}
    ambiguous_user_ids = set()

    memberships = (
        BusinessUser.objects.using(db_alias)
        .filter(is_active=True, business__is_active=True)
        .order_by("user_id", "business_id")
        .values_list("user_id", "business_id")
    )

    for user_id, business_id in memberships:
        if user_id in ambiguous_user_ids:
            continue

        existing_business_id = user_business_map.get(user_id)
        if existing_business_id is None:
            user_business_map[user_id] = business_id
            continue

        if existing_business_id != business_id:
            user_business_map.pop(user_id, None)
            ambiguous_user_ids.add(user_id)

    return user_business_map


def _get_legacy_business(Business, db_alias):
    existing_legacy_business = (
        Business.objects.using(db_alias)
        .filter(name="Legacy Workspace")
        .order_by("id")
        .first()
    )
    if existing_legacy_business:
        return existing_legacy_business

    base_slug = "legacy-workspace"
    slug = base_slug
    suffix = 2

    while Business.objects.using(db_alias).filter(slug=slug).exists():
        slug = f"{base_slug}-{suffix}"
        suffix += 1

    return Business.objects.using(db_alias).create(
        name="Legacy Workspace",
        slug=slug,
        is_active=True,
    )


def _get_fallback_business(Business, BusinessUser, db_alias):
    staff_business_id = (
        BusinessUser.objects.using(db_alias)
        .filter(
            is_active=True,
            business__is_active=True,
            role__in=("owner", "admin"),
            user__is_active=True,
            user__is_staff=True,
        )
        .order_by("business_id")
        .values_list("business_id", flat=True)
        .first()
    )

    if staff_business_id:
        return Business.objects.using(db_alias).get(pk=staff_business_id)

    return _get_legacy_business(Business, db_alias)


def backfill_existing_crm_businesses(apps, schema_editor):
    db_alias = schema_editor.connection.alias

    Business = apps.get_model("businesses", "Business")
    BusinessUser = apps.get_model("businesses", "BusinessUser")
    Client = apps.get_model("crm", "Client")
    Lead = apps.get_model("crm", "Lead")
    ActivityLog = apps.get_model("crm", "ActivityLog")

    needs_backfill = any(
        model.objects.using(db_alias).filter(business__isnull=True).exists()
        for model in (Client, Lead, ActivityLog)
    )
    if not needs_backfill:
        return

    user_business_map = _build_user_business_map(BusinessUser, db_alias)
    fallback_business = _get_fallback_business(Business, BusinessUser, db_alias)
    fallback_business_id = fallback_business.pk

    client_ids_by_business = defaultdict(list)
    clients_without_business = (
        Client.objects.using(db_alias)
        .filter(business__isnull=True, assigned_to_id__isnull=False)
        .values_list("id", "assigned_to_id")
    )
    for client_id, user_id in clients_without_business:
        business_id = user_business_map.get(user_id)
        if business_id:
            client_ids_by_business[business_id].append(client_id)

    for business_id, client_ids in client_ids_by_business.items():
        Client.objects.using(db_alias).filter(
            pk__in=client_ids,
            business__isnull=True,
        ).update(business_id=business_id)

    Client.objects.using(db_alias).filter(business__isnull=True).update(
        business_id=fallback_business_id
    )

    Lead.objects.using(db_alias).filter(business__isnull=True).update(
        business_id=fallback_business_id
    )

    client_business_map = dict(
        Client.objects.using(db_alias)
        .exclude(business__isnull=True)
        .values_list("id", "business_id")
    )
    lead_business_map = dict(
        Lead.objects.using(db_alias)
        .exclude(business__isnull=True)
        .values_list("id", "business_id")
    )

    activity_ids_by_business = defaultdict(list)
    activity_logs_without_business = (
        ActivityLog.objects.using(db_alias)
        .filter(business__isnull=True)
        .values_list("id", "client_id", "lead_id", "actor_id")
    )
    for activity_id, client_id, lead_id, actor_id in activity_logs_without_business:
        business_id = None

        if client_id:
            business_id = client_business_map.get(client_id)
        if business_id is None and lead_id:
            business_id = lead_business_map.get(lead_id)
        if business_id is None and actor_id:
            business_id = user_business_map.get(actor_id)
        if business_id is None:
            business_id = fallback_business_id

        activity_ids_by_business[business_id].append(activity_id)

    for business_id, activity_ids in activity_ids_by_business.items():
        ActivityLog.objects.using(db_alias).filter(
            pk__in=activity_ids,
            business__isnull=True,
        ).update(business_id=business_id)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_saasuserprofile"),
        ("businesses", "0001_initial"),
        ("crm", "0006_activitylog_business_client_business_lead_business"),
    ]

    operations = [
        migrations.RunPython(
            backfill_existing_crm_businesses,
            migrations.RunPython.noop,
        ),
    ]
