# Generated by Django 5.2.11 on 2026-05-20 23:32

import django.db.models.deletion
from django.db import migrations, models


LEGACY_CATEGORY_CODES = {
    "SEPTIC_PUMPING",
    "SEPTIC_INSTALLATION",
    "SEPTIC_REPAIR",
    "GREASE_TRAP_SERVICES",
    "UNCLOGGING_SERVICES",
    "OTHER",
}


def backfill_service_category_businesses(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Lead = apps.get_model("crm", "Lead")
    ServiceCategory = apps.get_model("crm", "ServiceCategory")

    categories = ServiceCategory.objects.using(db_alias).filter(business__isnull=True)

    for category in categories.iterator():
        linked_business_ids = set(
            Lead.objects.using(db_alias)
            .filter(category_id=category.id)
            .values_list("business_id", flat=True)
        )

        if not linked_business_ids:
            if category.code in LEGACY_CATEGORY_CODES:
                category.delete()
            continue

        if None in linked_business_ids:
            continue

        if len(linked_business_ids) != 1:
            continue

        category.business_id = linked_business_ids.pop()
        category.save(update_fields=["business"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        ("businesses", "0003_seed_default_clarivo_plans"),
        ("crm", "0007_backfill_existing_crm_businesses"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicecategory",
            options={"ordering": ["name", "pk"]},
        ),
        migrations.AddField(
            model_name="servicecategory",
            name="business",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_categories",
                to="businesses.business",
            ),
        ),
        migrations.AlterField(
            model_name="servicecategory",
            name="code",
            field=models.SlugField(blank=True, max_length=80),
        ),
        migrations.RunPython(
            backfill_service_category_businesses,
            migrations.RunPython.noop,
            atomic=True,
        ),
        migrations.AddIndex(
            model_name="servicecategory",
            index=models.Index(
                fields=["business", "is_active", "name"], name="crm_service_busines_87d8d7_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="servicecategory",
            constraint=models.UniqueConstraint(
                fields=("business", "code"), name="crm_service_category_unique_business_code"
            ),
        ),
    ]
