# Generated by Django 5.2.11 on 2026-05-21 00:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_business_business_type"),
        ("crm", "0008_alter_servicecategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("external_code", models.CharField(blank=True, max_length=80, null=True)),
                ("description", models.TextField(blank=True)),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00")),
                            django.core.validators.MaxValueValidator(Decimal("100.00")),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_services",
                        to="businesses.business",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="services",
                        to="crm.servicecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "pk"],
                "indexes": [
                    models.Index(
                        fields=["business", "is_active", "name"],
                        name="crm_busines_busines_186bf3_idx",
                    ),
                    models.Index(
                        fields=["business", "category", "is_active"],
                        name="crm_busines_busines_8bfd46_idx",
                    ),
                ],
            },
        ),
    ]
