# Generated by Django 5.2.11 on 2026-06-25 21:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0009_businessbookingsettings_weeklyavailability"),
        ("crm", "0009_businessservice"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessservice",
            name="booking_buffer_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
        migrations.AddField(
            model_name="businessservice",
            name="default_duration_minutes",
            field=models.PositiveIntegerField(
                blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="businessservice",
            name="is_bookable_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="businessservice",
            name="public_description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="businessservice",
            name="requires_manual_confirmation",
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name="businessservice",
            index=models.Index(
                fields=["business", "is_bookable_online", "is_active"],
                name="crm_busines_busines_17aa86_idx",
            ),
        ),
    ]
