# Generated by Django 5.2.11 on 2026-06-26 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0010_businessservice_booking_buffer_minutes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="preferred_end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="preferred_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="request_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_request", "Public request form"),
                    ("public_booking", "Public booking form"),
                    ("staff", "Staff-entered"),
                    ("other", "Other"),
                ],
                default="",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="requested_service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="requested_leads",
                to="crm.businessservice",
            ),
        ),
    ]
