# Generated by Django 5.2.11 on 2026-06-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0011_lead_public_booking_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="district",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
