# Generated by Django 5.2.11 on 2026-06-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0012_alter_client_district_alter_lead_district"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="request_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("public_request", "Public booking"),
                    ("public_booking", "Public booking"),
                    ("staff", "Staff-entered"),
                    ("other", "Other"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
