# Generated by Django 5.2.11 on 2026-09-07 15:44

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.crm.models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0021_business_data_operation"),
        ("crm", "0013_unify_public_booking_source_labels"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "import_type",
                    models.CharField(
                        choices=[
                            ("clients", "Clients"),
                            ("leads", "Leads"),
                            ("services", "Services"),
                        ],
                        max_length=20,
                    ),
                ),
                ("schema_version", models.CharField(max_length=20)),
                ("original_filename", models.CharField(max_length=255)),
                ("file_digest", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("validated", "Validated"),
                            ("ready", "Ready"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("rows_detected", models.PositiveIntegerField(default=0)),
                ("rows_valid", models.PositiveIntegerField(default=0)),
                ("rows_warning", models.PositiveIntegerField(default=0)),
                ("rows_error", models.PositiveIntegerField(default=0)),
                ("rows_created", models.PositiveIntegerField(default=0)),
                ("rows_updated", models.PositiveIntegerField(default=0)),
                ("rows_skipped", models.PositiveIntegerField(default=0)),
                (
                    "expires_at",
                    models.DateTimeField(default=apps.crm.models.default_import_job_expiry),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="businesses.business",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="crm_import_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["business", "import_type", "status"],
                        name="crm_importj_busines_a7f93f_idx",
                    ),
                    models.Index(
                        fields=["created_by", "status"], name="crm_importj_created_cdd5c4_idx"
                    ),
                ],
            },
        ),
    ]
