# Generated by Django 5.2.11 on 2026-09-24 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0014_importjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="client_status",
            field=models.CharField(
                choices=[
                    ("LEAD", "Lead"),
                    ("PROSPECT", "Prospect"),
                    ("ACTIVE", "Active Client"),
                    ("INACTIVE", "Inactive"),
                    ("ARCHIVED", "Archived"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
